title: CORENET X Code of Practice Info site
url: https://info.corenet.gov.sg
favicon: /images/CXLogo.png
colors:
  primary-color: "#00089c"
  secondary-color: "#4372d6"
  media-colors:
    - title: media-color-one
      color: "#49759a"
    - title: media-color-two
      color: "#744d9f"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: >-
  This website is intended to assist project teams in the Built Environment in
  their understanding on

  preparation for CORENET X submissions. The Code of Practice sets out recommended procedures and good practices to address common queries (e.g. what regulatory data to submit when and how to represent that data in 3D BIM or other formats). The Code of Practice is aimed at providing a consistent approach and standard on CORENET X submissions for the Built Environment project teams.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d38zvb4vmtcmgg.amplifyapp.com
prod: https://master.d38zvb4vmtcmgg.amplifyapp.com
shareicon: /images/CXLogo.png
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: ifc-sg
